import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "@/lib/authOptions";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  if (session !== null) {
    return redirect("/");
  }
  return (
    <html lang="en">
      <body className={`${epilogue.className} relative overflow-x-hidden`}>
        <main className="md:grid md:grid-cols-2">
          <div className="relative h-screen hidden md:block">
            <div className="absolute w-full h-full">
              <Image src="/images/bg-auth.png" alt="/images/bg-auth.png" fill objectFit="cover" objectPosition="top" />
            </div>
          </div>
          <div className="w-full relative">
            <div className="p-10 md:absolute md:top-1/2 md:left-1/2 md:-translate-x-1/2 md:-translate-y-1/2">{children}</div>
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
